version: '3'

services:

  gympassclone-pg:
    image: "bitnami/postgresql"
    ports:
      - "5432:5432"
    environment:
      - POSTGRESQL_USERNAME=postgres
      - POSTGRESQL_PASSWORD=postgres
      - POSTGRESQL_DATABASE=gympassclone
      